version: '3.8'

services:
  laravel:
    image: 'laravel:latest'
    container_name: laravel_app
    ports:
      - '8000:8000' 
    volumes:
      - ./laravel:/var/www/html 
    environment:
      - APP_ENV=local
      - APP_KEY=base64:cqK4VQdfC8q4IhX9oADsFkD2gBrHbjXO1NzweuUdHgg=

  nuxt:
    image: 'nuxt:latest'
    container_name: nuxt_app
    ports:
      - '3000:3000' 
    volumes:
      - ./nuxt:/app 
    environment:
      - NODE_ENV=development
